// Code generated by internal/cmd/genmaps; DO NOT EDIT.

package chalkfn

import "github.com/apache/arrow-go/v18/arrow"

// Map1 builds a Function that applies fn to each row of a one-column input.
// Rows where the input is null produce a null output without calling fn, and
// an error from fn fails the whole batch.
//
//	chalkfn.Register(chalkfn.Map1("add_one", "x", "result",
//		func(x int64) (int64, error) { return x + 1, nil }))
func Map1[A, R Scalar](name, a, result string, fn func(A) (R, error)) Function {
	return Function{
		Name:   name,
		Input:  Schema(Col(a, ArrowType[A]())),
		Output: Schema(Col(result, ArrowType[R]())),
		Fn: rowwise[R](func(cols []arrow.Array, out func(R), row int) error {
			r, err := fn(valueAt[A](cols[0], row))
			if err == nil {
				out(r)
			}
			return err
		}),
	}
}

// Map2 is [Map1] for 2 input columns, named by the string arguments
// before result in the order fn takes them.
func Map2[A, B, R Scalar](name, a, b, result string, fn func(A, B) (R, error)) Function {
	return Function{
		Name:   name,
		Input:  Schema(Col(a, ArrowType[A]()), Col(b, ArrowType[B]())),
		Output: Schema(Col(result, ArrowType[R]())),
		Fn: rowwise[R](func(cols []arrow.Array, out func(R), row int) error {
			r, err := fn(valueAt[A](cols[0], row), valueAt[B](cols[1], row))
			if err == nil {
				out(r)
			}
			return err
		}),
	}
}

// Map3 is [Map1] for 3 input columns, named by the string arguments
// before result in the order fn takes them.
func Map3[A, B, C, R Scalar](name, a, b, c, result string, fn func(A, B, C) (R, error)) Function {
	return Function{
		Name:   name,
		Input:  Schema(Col(a, ArrowType[A]()), Col(b, ArrowType[B]()), Col(c, ArrowType[C]())),
		Output: Schema(Col(result, ArrowType[R]())),
		Fn: rowwise[R](func(cols []arrow.Array, out func(R), row int) error {
			r, err := fn(valueAt[A](cols[0], row), valueAt[B](cols[1], row), valueAt[C](cols[2], row))
			if err == nil {
				out(r)
			}
			return err
		}),
	}
}

// Map4 is [Map1] for 4 input columns, named by the string arguments
// before result in the order fn takes them.
func Map4[A, B, C, D, R Scalar](name, a, b, c, d, result string, fn func(A, B, C, D) (R, error)) Function {
	return Function{
		Name:   name,
		Input:  Schema(Col(a, ArrowType[A]()), Col(b, ArrowType[B]()), Col(c, ArrowType[C]()), Col(d, ArrowType[D]())),
		Output: Schema(Col(result, ArrowType[R]())),
		Fn: rowwise[R](func(cols []arrow.Array, out func(R), row int) error {
			r, err := fn(valueAt[A](cols[0], row), valueAt[B](cols[1], row), valueAt[C](cols[2], row), valueAt[D](cols[3], row))
			if err == nil {
				out(r)
			}
			return err
		}),
	}
}

// Map5 is [Map1] for 5 input columns, named by the string arguments
// before result in the order fn takes them.
func Map5[A, B, C, D, E, R Scalar](name, a, b, c, d, e, result string, fn func(A, B, C, D, E) (R, error)) Function {
	return Function{
		Name:   name,
		Input:  Schema(Col(a, ArrowType[A]()), Col(b, ArrowType[B]()), Col(c, ArrowType[C]()), Col(d, ArrowType[D]()), Col(e, ArrowType[E]())),
		Output: Schema(Col(result, ArrowType[R]())),
		Fn: rowwise[R](func(cols []arrow.Array, out func(R), row int) error {
			r, err := fn(valueAt[A](cols[0], row), valueAt[B](cols[1], row), valueAt[C](cols[2], row), valueAt[D](cols[3], row), valueAt[E](cols[4], row))
			if err == nil {
				out(r)
			}
			return err
		}),
	}
}

// Map6 is [Map1] for 6 input columns, named by the string arguments
// before result in the order fn takes them.
func Map6[A, B, C, D, E, F, R Scalar](name, a, b, c, d, e, f, result string, fn func(A, B, C, D, E, F) (R, error)) Function {
	return Function{
		Name:   name,
		Input:  Schema(Col(a, ArrowType[A]()), Col(b, ArrowType[B]()), Col(c, ArrowType[C]()), Col(d, ArrowType[D]()), Col(e, ArrowType[E]()), Col(f, ArrowType[F]())),
		Output: Schema(Col(result, ArrowType[R]())),
		Fn: rowwise[R](func(cols []arrow.Array, out func(R), row int) error {
			r, err := fn(valueAt[A](cols[0], row), valueAt[B](cols[1], row), valueAt[C](cols[2], row), valueAt[D](cols[3], row), valueAt[E](cols[4], row), valueAt[F](cols[5], row))
			if err == nil {
				out(r)
			}
			return err
		}),
	}
}

// Map7 is [Map1] for 7 input columns, named by the string arguments
// before result in the order fn takes them.
func Map7[A, B, C, D, E, F, G, R Scalar](name, a, b, c, d, e, f, g, result string, fn func(A, B, C, D, E, F, G) (R, error)) Function {
	return Function{
		Name:   name,
		Input:  Schema(Col(a, ArrowType[A]()), Col(b, ArrowType[B]()), Col(c, ArrowType[C]()), Col(d, ArrowType[D]()), Col(e, ArrowType[E]()), Col(f, ArrowType[F]()), Col(g, ArrowType[G]())),
		Output: Schema(Col(result, ArrowType[R]())),
		Fn: rowwise[R](func(cols []arrow.Array, out func(R), row int) error {
			r, err := fn(valueAt[A](cols[0], row), valueAt[B](cols[1], row), valueAt[C](cols[2], row), valueAt[D](cols[3], row), valueAt[E](cols[4], row), valueAt[F](cols[5], row), valueAt[G](cols[6], row))
			if err == nil {
				out(r)
			}
			return err
		}),
	}
}

// Map8 is [Map1] for 8 input columns, named by the string arguments
// before result in the order fn takes them.
func Map8[A, B, C, D, E, F, G, H, R Scalar](name, a, b, c, d, e, f, g, h, result string, fn func(A, B, C, D, E, F, G, H) (R, error)) Function {
	return Function{
		Name:   name,
		Input:  Schema(Col(a, ArrowType[A]()), Col(b, ArrowType[B]()), Col(c, ArrowType[C]()), Col(d, ArrowType[D]()), Col(e, ArrowType[E]()), Col(f, ArrowType[F]()), Col(g, ArrowType[G]()), Col(h, ArrowType[H]())),
		Output: Schema(Col(result, ArrowType[R]())),
		Fn: rowwise[R](func(cols []arrow.Array, out func(R), row int) error {
			r, err := fn(valueAt[A](cols[0], row), valueAt[B](cols[1], row), valueAt[C](cols[2], row), valueAt[D](cols[3], row), valueAt[E](cols[4], row), valueAt[F](cols[5], row), valueAt[G](cols[6], row), valueAt[H](cols[7], row))
			if err == nil {
				out(r)
			}
			return err
		}),
	}
}

// Map9 is [Map1] for 9 input columns, named by the string arguments
// before result in the order fn takes them.
func Map9[A, B, C, D, E, F, G, H, I, R Scalar](name, a, b, c, d, e, f, g, h, i, result string, fn func(A, B, C, D, E, F, G, H, I) (R, error)) Function {
	return Function{
		Name:   name,
		Input:  Schema(Col(a, ArrowType[A]()), Col(b, ArrowType[B]()), Col(c, ArrowType[C]()), Col(d, ArrowType[D]()), Col(e, ArrowType[E]()), Col(f, ArrowType[F]()), Col(g, ArrowType[G]()), Col(h, ArrowType[H]()), Col(i, ArrowType[I]())),
		Output: Schema(Col(result, ArrowType[R]())),
		Fn: rowwise[R](func(cols []arrow.Array, out func(R), row int) error {
			r, err := fn(valueAt[A](cols[0], row), valueAt[B](cols[1], row), valueAt[C](cols[2], row), valueAt[D](cols[3], row), valueAt[E](cols[4], row), valueAt[F](cols[5], row), valueAt[G](cols[6], row), valueAt[H](cols[7], row), valueAt[I](cols[8], row))
			if err == nil {
				out(r)
			}
			return err
		}),
	}
}
