// Command genmaps writes chalkfn's Map1 through Map9 helpers, which differ
// only in arity.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

const maxArity = 9

func main() {
	out := flag.String("o", "maps_gen.go", "output file")
	flag.Parse()

	var b bytes.Buffer
	b.WriteString(`// Code generated by internal/cmd/genmaps; DO NOT EDIT.

package chalkfn

import "github.com/apache/arrow-go/v18/arrow"
`)
	for n := 1; n <= maxArity; n++ {
		writeMap(&b, n)
	}
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("formatting generated code: %v\n%s", err, b.Bytes())
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
}

func writeMap(b *bytes.Buffer, n int) {
	var types, cols, cells, reads []string
	for i := 0; i < n; i++ {
		t := string(rune('A' + i))
		c := strings.ToLower(t)
		types = append(types, t)
		cols = append(cols, c)
		cells = append(cells, fmt.Sprintf("Col(%s, ArrowType[%s]())", c, t))
		reads = append(reads, fmt.Sprintf("valueAt[%s](cols[%d], row)", t, i))
	}
	if n == 1 {
		fmt.Fprint(b, `
// Map1 builds a Function that applies fn to each row of a one-column input.
// Rows where the input is null produce a null output without calling fn, and
// an error from fn fails the whole batch.
//
//	chalkfn.Register(chalkfn.Map1("add_one", "x", "result",
//		func(x int64) (int64, error) { return x + 1, nil }))
`)
	} else {
		fmt.Fprintf(b, "\n// Map%d is [Map1] for %d input columns, named by the string arguments\n// before result in the order fn takes them.\n", n, n)
	}
	fmt.Fprintf(b, `func Map%d[%s, R Scalar](name, %s, result string, fn func(%s) (R, error)) Function {
	return Function{
		Name:   name,
		Input:  Schema(%s),
		Output: Schema(Col(result, ArrowType[R]())),
		Fn: rowwise[R](func(cols []arrow.Array, out func(R), row int) error {
			r, err := fn(%s)
			if err == nil {
				out(r)
			}
			return err
		}),
	}
}
`, n, strings.Join(types, ", "), strings.Join(cols, ", "), strings.Join(types, ", "),
		strings.Join(cells, ", "), strings.Join(reads, ", "))
}
